on:
  push:
    branches: '**'

jobs:
  push:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/displayr/r-server-skinny-base:basic
      credentials:
        username: jrwishart
        password: ${{ secrets.JUSTIN_GITHUB_PAT }}
    steps:
      - name: Install stuff
        run: |
          apt-fast install -y git
          R -e 'install.packages("getPass")'
          R -e 'remotes::install_github("flipDevTools")'
        env:
          GITHUB_PAT: ${{ secrets.JUSTIN_GITHUB_PAT }}
      - name: Pull code
        uses: actions/checkout@v2
      - name: Check directory #DELETE ME!!
        run: ls
      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v1
      - name: Run tests
        run: R -e "devtools::test()"
        working-directory: /flipU
