on:
  push:
    branches: '**'

jobs:
  push:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/displayr/r-server-skinny-base:basic
      credentials:
        username: jrwishart
        password: ${{ secrets.JUSTIN_GITHUB_PAT }}
    steps:
      - name: Install stuff
        run: |
          apt-fast install -y git
        env:
          GITHUB_PAT: ${{ secrets.JUSTIN_GITHUB_PAT }}
      - name: Pull code
        uses: actions/checkout@v2
      - name: Run R CMD check and test
        run: rcmdcheck::rcmdcheck(args = c("--as-cran", "--no-manual", "--no-build-vignettes"), build_args = c("--no-build-vignettes", "--no-resave-data"))
        shell: Rscript {0}
      - name: Run tests
        run: devtools::test()
        shell: Rscript {0}
